"""Add last_known_weekly_hours

Revision ID: 9b49af42f54d
Revises: 0007
Create Date: 2026-08-27 07:58:57.650536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b49af42f54d'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('coding_sandbox_submissions_profile_id_fkey'), 'coding_sandbox_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'coding_sandbox_submissions', 'learner_profiles', ['profile_id'], ['id'])
    op.add_column('learner_profiles', sa.Column('last_known_weekly_hours', sa.Float(), nullable=False, server_default='10.0'))
    op.drop_constraint(op.f('mentor_applications_user_id_fkey'), 'mentor_applications', type_='foreignkey')
    op.create_foreign_key(None, 'mentor_applications', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('fk_resources_submitted_by'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'users', ['submitted_by_id'], ['id'])
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_resources_submitted_by'), 'resources', 'users', ['submitted_by_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'mentor_applications', type_='foreignkey')
    op.create_foreign_key(op.f('mentor_applications_user_id_fkey'), 'mentor_applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('learner_profiles', 'last_known_weekly_hours')
    op.drop_constraint(None, 'coding_sandbox_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('coding_sandbox_submissions_profile_id_fkey'), 'coding_sandbox_submissions', 'learner_profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
